//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to {0}.
        /// </summary>
        internal static string CantConnectTo {
            get {
                return ResourceManager.GetString("CantConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not follow the ubiquitous encryption policy.
        /// </summary>
        internal static string DomainDoesNotFollowEncryptionPolicy {
            get {
                return ResourceManager.GetString("DomainDoesNotFollowEncryptionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid operator.
        /// </summary>
        internal static string DomainIsNotAValidOperator {
            get {
                return ResourceManager.GetString("DomainIsNotAValidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Other&gt;.
        /// </summary>
        internal static string OperatorDomainOther {
            get {
                return ResourceManager.GetString("OperatorDomainOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter manually.
        /// </summary>
        internal static string QrEnterManually {
            get {
                return ResourceManager.GetString("QrEnterManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string QrScanAddButton {
            get {
                return ResourceManager.GetString("QrScanAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan code.
        /// </summary>
        internal static string QrScanCode {
            get {
                return ResourceManager.GetString("QrScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Identity:.
        /// </summary>
        internal static string QrScanLegalIdentity {
            get {
                return ResourceManager.GetString("QrScanLegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align the QR-Code within the frame.
        /// </summary>
        internal static string QrScanOverlay {
            get {
                return ResourceManager.GetString("QrScanOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Operator.
        /// </summary>
        internal static string SelectOperator {
            get {
                return ResourceManager.GetString("SelectOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}.
        /// </summary>
        internal static string UnableToConnectTo {
            get {
                return ResourceManager.GetString("UnableToConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TAG Xamarin App!.
        /// </summary>
        internal static string WelcomeToTagHeading {
            get {
                return ResourceManager.GetString("WelcomeToTagHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect to the TAG network, you need to select an operator. Please select one from the list below..
        /// </summary>
        internal static string WelcomeToTagSubheading {
            get {
                return ResourceManager.GetString("WelcomeToTagSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating network identity.
        /// </summary>
        internal static string XmppState_Authenticating {
            get {
                return ResourceManager.GetString("XmppState_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding connection.
        /// </summary>
        internal static string XmppState_Binding {
            get {
                return ResourceManager.GetString("XmppState_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string XmppState_Connected {
            get {
                return ResourceManager.GetString("XmppState_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection.
        /// </summary>
        internal static string XmppState_Connecting {
            get {
                return ResourceManager.GetString("XmppState_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string XmppState_Error {
            get {
                return ResourceManager.GetString("XmppState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching roster.
        /// </summary>
        internal static string XmppState_FetchingRoster {
            get {
                return ResourceManager.GetString("XmppState_FetchingRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string XmppState_Offline {
            get {
                return ResourceManager.GetString("XmppState_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering with broker.
        /// </summary>
        internal static string XmppState_Registering {
            get {
                return ResourceManager.GetString("XmppState_Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting session.
        /// </summary>
        internal static string XmppState_RequestingSession {
            get {
                return ResourceManager.GetString("XmppState_RequestingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting presence.
        /// </summary>
        internal static string XmppState_SettingPresence {
            get {
                return ResourceManager.GetString("XmppState_SettingPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting connection.
        /// </summary>
        internal static string XmppState_StartingEncryption {
            get {
                return ResourceManager.GetString("XmppState_StartingEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiating stream.
        /// </summary>
        internal static string XmppState_StreamNegotiation {
            get {
                return ResourceManager.GetString("XmppState_StreamNegotiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream established.
        /// </summary>
        internal static string XmppState_StreamOpened {
            get {
                return ResourceManager.GetString("XmppState_StreamOpened", resourceCulture);
            }
        }
    }
}
