//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name {0} is already taken. Choose another..
        /// </summary>
        internal static string AccountNameAlreadyTaken {
            get {
                return ResourceManager.GetString("AccountNameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name is invalid.
        /// </summary>
        internal static string AccountNameIsInvalid {
            get {
                return ResourceManager.GetString("AccountNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (row 2).
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition has been sent to your peer.
        /// </summary>
        internal static string APetitionHasBeenSentToYourPeer {
            get {
                return ResourceManager.GetString("APetitionHasBeenSentToYourPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to {0}.
        /// </summary>
        internal static string CantConnectTo {
            get {
                return ResourceManager.GetString("CantConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose account.
        /// </summary>
        internal static string ChooseAccount {
            get {
                return ResourceManager.GetString("ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define PIN.
        /// </summary>
        internal static string DefinePin {
            get {
                return ResourceManager.GetString("DefinePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not follow the ubiquitous encryption policy.
        /// </summary>
        internal static string DomainDoesNotFollowEncryptionPolicy {
            get {
                return ResourceManager.GetString("DomainDoesNotFollowEncryptionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid operator.
        /// </summary>
        internal static string DomainIsNotAValidOperator {
            get {
                return ResourceManager.GetString("DomainIsNotAValidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name is invalid.
        /// </summary>
        internal static string DomainNameIsInvalid {
            get {
                return ResourceManager.GetString("DomainNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite peer to review.
        /// </summary>
        internal static string InvitePeerToReview {
            get {
                return ResourceManager.GetString("InvitePeerToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name(s).
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name(s).
        /// </summary>
        internal static string MiddleNames {
            get {
                return ResourceManager.GetString("MiddleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to the operator.
        /// </summary>
        internal static string NotConnectedToTheOperator {
            get {
                return ResourceManager.GetString("NotConnectedToTheOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator does not support legal identities and smart contracts.
        /// </summary>
        internal static string OperatorDoesNotSupportLegalIdentitiesAndSmartContracts {
            get {
                return ResourceManager.GetString("OperatorDoesNotSupportLegalIdentitiesAndSmartContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator {0} does not support registration of new accounts.
        /// </summary>
        internal static string OperatorDoesNotSupportRegisteringNewAccounts {
            get {
                return ResourceManager.GetString("OperatorDoesNotSupportRegisteringNewAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Other&gt;.
        /// </summary>
        internal static string OperatorDomainOther {
            get {
                return ResourceManager.GetString("OperatorDomainOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid.
        /// </summary>
        internal static string PasswordIsInvalid {
            get {
                return ResourceManager.GetString("PasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer review accepted.
        /// </summary>
        internal static string PeerReviewAccepted {
            get {
                return ResourceManager.GetString("PeerReviewAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer review rejected.
        /// </summary>
        internal static string PeerReviewRejected {
            get {
                return ResourceManager.GetString("PeerReviewRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal/legal information.
        /// </summary>
        internal static string PersonalLegalInformation {
            get {
                return ResourceManager.GetString("PersonalLegalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to get a wallet, perform transactions and sign smart contracts, you need an attested personal or legal identity assigned to your account..
        /// </summary>
        internal static string PersonalLegalInfoText {
            get {
                return ResourceManager.GetString("PersonalLegalInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal number.
        /// </summary>
        internal static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The personal number does not match national personal number regulations.
        /// </summary>
        internal static string PersonalNumberDoesNotMatchCountry {
            get {
                return ResourceManager.GetString("PersonalNumberDoesNotMatchCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The personal number does not match national personal number regulations. Expected format: .
        /// </summary>
        internal static string PersonalNumberDoesNotMatchCountry_ExpectedFormat {
            get {
                return ResourceManager.GetString("PersonalNumberDoesNotMatchCountry_ExpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition sent.
        /// </summary>
        internal static string PetitionSent {
            get {
                return ResourceManager.GetString("PetitionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is too large.
        /// </summary>
        internal static string PhotoIsTooLarge {
            get {
                return ResourceManager.GetString("PhotoIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick photo.
        /// </summary>
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN number must not include leading or trailing whitespace..
        /// </summary>
        internal static string PinMustNotIncludeWhitespace {
            get {
                return ResourceManager.GetString("PinMustNotIncludeWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN or password.
        /// </summary>
        internal static string PinOrPassword {
            get {
                return ResourceManager.GetString("PinOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PINs do not match.
        /// </summary>
        internal static string PinsDoNotMatch {
            get {
                return ResourceManager.GetString("PinsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN number too short. At least 8 numbers (or characters) are required..
        /// </summary>
        internal static string PinTooShort {
            get {
                return ResourceManager.GetString("PinTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter manually.
        /// </summary>
        internal static string QrEnterManually {
            get {
                return ResourceManager.GetString("QrEnterManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string QrScanAddButton {
            get {
                return ResourceManager.GetString("QrScanAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan code.
        /// </summary>
        internal static string QrScanCode {
            get {
                return ResourceManager.GetString("QrScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Identity:.
        /// </summary>
        internal static string QrScanLegalIdentity {
            get {
                return ResourceManager.GetString("QrScanLegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align the QR-Code within the frame.
        /// </summary>
        internal static string QrScanOverlay {
            get {
                return ResourceManager.GetString("QrScanOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region or State.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        internal static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype PIN or password.
        /// </summary>
        internal static string RetypePinOrPassword {
            get {
                return ResourceManager.GetString("RetypePinOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a photo is not supported on this device.
        /// </summary>
        internal static string SelectingAPhotoIsNotSupported {
            get {
                return ResourceManager.GetString("SelectingAPhotoIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Operator.
        /// </summary>
        internal static string SelectOperator {
            get {
                return ResourceManager.GetString("SelectOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking a photo is not supported on this device.
        /// </summary>
        internal static string TakingAPhotoIsNotSupported {
            get {
                return ResourceManager.GetString("TakingAPhotoIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the connection is {0}.
        /// </summary>
        internal static string ThePasswordForTheConnectionIs {
            get {
                return ResourceManager.GetString("ThePasswordForTheConnectionIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified code is not a legal identity.
        /// </summary>
        internal static string TheSpecifiedCodeIsNotALegalIdentity {
            get {
                return ResourceManager.GetString("TheSpecifiedCodeIsNotALegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect to {0}, you need an account. Do you want to create one, or use an existing account?.
        /// </summary>
        internal static string ToConnectToDomainYouNeedAnAccount {
            get {
                return ResourceManager.GetString("ToConnectToDomainYouNeedAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate with {0}.
        /// </summary>
        internal static string UnableToAuthenticateWith {
            get {
                return ResourceManager.GetString("UnableToAuthenticateWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}.
        /// </summary>
        internal static string UnableToConnectTo {
            get {
                return ResourceManager.GetString("UnableToConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use existing.
        /// </summary>
        internal static string UseExisting {
            get {
                return ResourceManager.GetString("UseExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your identity information has to be validated before it can be approved. This can be done manually by your operator. It can also be done by peers..
        /// </summary>
        internal static string ValidateIdentityInfo1Text {
            get {
                return ResourceManager.GetString("ValidateIdentityInfo1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To invite a peer to review your application, you need to scan the ID code of the peer you wish to invite. They will be able to see and review your application. When sufficient peers have reviewed your information, and certified it is correct, the operator will automatically approve your application. The information about who reviewed your identity will be encoded into the reviewed identity itself..
        /// </summary>
        internal static string ValidateIdentityInfo2Text {
            get {
                return ResourceManager.GetString("ValidateIdentityInfo2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the current status of the application below..
        /// </summary>
        internal static string ValidateIdentityInfo3Text {
            get {
                return ResourceManager.GetString("ValidateIdentityInfo3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating information.
        /// </summary>
        internal static string ValidatingInformation {
            get {
                return ResourceManager.GetString("ValidatingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TAG Xamarin App!.
        /// </summary>
        internal static string WelcomeToTagHeading {
            get {
                return ResourceManager.GetString("WelcomeToTagHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect to the TAG network, you need to select an operator. Please select one from the list below..
        /// </summary>
        internal static string WelcomeToTagSubheading {
            get {
                return ResourceManager.GetString("WelcomeToTagSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating network identity.
        /// </summary>
        internal static string XmppState_Authenticating {
            get {
                return ResourceManager.GetString("XmppState_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding connection.
        /// </summary>
        internal static string XmppState_Binding {
            get {
                return ResourceManager.GetString("XmppState_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string XmppState_Connected {
            get {
                return ResourceManager.GetString("XmppState_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection.
        /// </summary>
        internal static string XmppState_Connecting {
            get {
                return ResourceManager.GetString("XmppState_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string XmppState_Error {
            get {
                return ResourceManager.GetString("XmppState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching roster.
        /// </summary>
        internal static string XmppState_FetchingRoster {
            get {
                return ResourceManager.GetString("XmppState_FetchingRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string XmppState_Offline {
            get {
                return ResourceManager.GetString("XmppState_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering with broker.
        /// </summary>
        internal static string XmppState_Registering {
            get {
                return ResourceManager.GetString("XmppState_Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting session.
        /// </summary>
        internal static string XmppState_RequestingSession {
            get {
                return ResourceManager.GetString("XmppState_RequestingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting presence.
        /// </summary>
        internal static string XmppState_SettingPresence {
            get {
                return ResourceManager.GetString("XmppState_SettingPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting connection.
        /// </summary>
        internal static string XmppState_StartingEncryption {
            get {
                return ResourceManager.GetString("XmppState_StartingEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiating stream.
        /// </summary>
        internal static string XmppState_StreamNegotiation {
            get {
                return ResourceManager.GetString("XmppState_StreamNegotiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream established.
        /// </summary>
        internal static string XmppState_StreamOpened {
            get {
                return ResourceManager.GetString("XmppState_StreamOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can protect your wallet and sensitive information by adding an additional PIN number or password..
        /// </summary>
        internal static string YouCanProtectYourWalletPinInfo {
            get {
                return ResourceManager.GetString("YouCanProtectYourWalletPinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a country.
        /// </summary>
        internal static string YouNeedToProvideACountry {
            get {
                return ResourceManager.GetString("YouNeedToProvideACountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide a first name.
        /// </summary>
        internal static string YouNeedToProvideAFirstName {
            get {
                return ResourceManager.GetString("YouNeedToProvideAFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide at least one last name.
        /// </summary>
        internal static string YouNeedToProvideALastName {
            get {
                return ResourceManager.GetString("YouNeedToProvideALastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide a personal or social security number.
        /// </summary>
        internal static string YouNeedToProvideAPersonalNumber {
            get {
                return ResourceManager.GetString("YouNeedToProvideAPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip or Postal Code.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
