//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name {0} is already taken. Choose another..
        /// </summary>
        internal static string AccountNameAlreadyTaken {
            get {
                return ResourceManager.GetString("AccountNameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name is invalid.
        /// </summary>
        internal static string AccountNameIsInvalid {
            get {
                return ResourceManager.GetString("AccountNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add part.
        /// </summary>
        internal static string AddPart {
            get {
                return ResourceManager.GetString("AddPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (row 2).
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A peer review you requested has been accepted..
        /// </summary>
        internal static string APeerReviewYouhaveRequestedHasBeenAccepted {
            get {
                return ResourceManager.GetString("APeerReviewYouhaveRequestedHasBeenAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A peer review you requested has been rejected, due to a signature error..
        /// </summary>
        internal static string APeerYouRequestedToReviewHasBeenRejectedDueToSignatureError {
            get {
                return ResourceManager.GetString("APeerYouRequestedToReviewHasBeenRejectedDueToSignatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A peer you requested to review your application, has rejected to approve it..
        /// </summary>
        internal static string APeerYouRequestedToReviewHasRejected {
            get {
                return ResourceManager.GetString("APeerYouRequestedToReviewHasRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition has been sent to the parts of the contract. If any of the parts accepts the petition, the contract information will be displayed on the screen..
        /// </summary>
        internal static string APetitionHasBeenSentToTheContract {
            get {
                return ResourceManager.GetString("APetitionHasBeenSentToTheContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition has been sent to the owner of the identity. If the owner accepts the petition, the identity information will be displayed on the screen..
        /// </summary>
        internal static string APetitionHasBeenSentToTheOwner {
            get {
                return ResourceManager.GetString("APetitionHasBeenSentToTheOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition has been sent to your peer.
        /// </summary>
        internal static string APetitionHasBeenSentToYourPeer {
            get {
                return ResourceManager.GetString("APetitionHasBeenSentToYourPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Information.
        /// </summary>
        internal static string ApproveInformation {
            get {
                return ResourceManager.GetString("ApproveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving (optional).
        /// </summary>
        internal static string Archiving_Optional {
            get {
                return ResourceManager.GetString("Archiving_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving (required).
        /// </summary>
        internal static string Archiving_Required {
            get {
                return ResourceManager.GetString("Archiving_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to report your legal identity as compromized, stolen or hacked?.
        /// </summary>
        internal static string AreYouSureYouWantToReportYourLegalIdentityAsCompromized {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToReportYourLegalIdentityAsCompromized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revoke your legal identity from the application?.
        /// </summary>
        internal static string AreYouSureYouWantToRevokeYourLegalIdentity {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRevokeYourLegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can act as template.
        /// </summary>
        internal static string CanActAsTemplate {
            get {
                return ResourceManager.GetString("CanActAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to {0}.
        /// </summary>
        internal static string CantConnectTo {
            get {
                return ResourceManager.GetString("CantConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose account.
        /// </summary>
        internal static string ChooseAccount {
            get {
                return ResourceManager.GetString("ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Signature.
        /// </summary>
        internal static string ClientSignature {
            get {
                return ResourceManager.GetString("ClientSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is information related to a client signature..
        /// </summary>
        internal static string ClientSignatureInformationInfoText {
            get {
                return ResourceManager.GetString("ClientSignatureInformationInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Signatures.
        /// </summary>
        internal static string ClientSignatures {
            get {
                return ResourceManager.GetString("ClientSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic signatures made by different parts are listed below..
        /// </summary>
        internal static string ClientSignaturesInfoText {
            get {
                return ResourceManager.GetString("ClientSignaturesInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Category.
        /// </summary>
        internal static string ContractCategory {
            get {
                return ResourceManager.GetString("ContractCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract has been deleted..
        /// </summary>
        internal static string ContractHasBeenDeleted {
            get {
                return ResourceManager.GetString("ContractHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract has been obsoleted..
        /// </summary>
        internal static string ContractHasBeenObsoleted {
            get {
                return ResourceManager.GetString("ContractHasBeenObsoleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract ID.
        /// </summary>
        internal static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select contract role first, and then try again..
        /// </summary>
        internal static string ContractRoleMustBeSelected {
            get {
                return ResourceManager.GetString("ContractRoleMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        internal static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract successfully signed..
        /// </summary>
        internal static string ContractSuccessfullySigned {
            get {
                return ResourceManager.GetString("ContractSuccessfullySigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        internal static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator and parts.
        /// </summary>
        internal static string ContractVisibility_CreatorAndParts {
            get {
                return ResourceManager.GetString("ContractVisibility_CreatorAndParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain and parts.
        /// </summary>
        internal static string ContractVisibility_DomainAndParts {
            get {
                return ResourceManager.GetString("ContractVisibility_DomainAndParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public, not searchable.
        /// </summary>
        internal static string ContractVisibility_Public {
            get {
                return ResourceManager.GetString("ContractVisibility_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public and searchable.
        /// </summary>
        internal static string ContractVisibility_PublicSearchable {
            get {
                return ResourceManager.GetString("ContractVisibility_PublicSearchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select contract visibility first, and then try again..
        /// </summary>
        internal static string ContractVisibilityMustBeSelected {
            get {
                return ResourceManager.GetString("ContractVisibilityMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you please review my identity information?.
        /// </summary>
        internal static string CouldYouPleaseReviewMyIdentityInformation {
            get {
                return ResourceManager.GetString("CouldYouPleaseReviewMyIdentityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define PIN.
        /// </summary>
        internal static string DefinePin {
            get {
                return ResourceManager.GetString("DefinePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete contract.
        /// </summary>
        internal static string DeleteContract {
            get {
                return ResourceManager.GetString("DeleteContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digest.
        /// </summary>
        internal static string Digest {
            get {
                return ResourceManager.GetString("Digest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not follow the ubiquitous encryption policy.
        /// </summary>
        internal static string DomainDoesNotFollowEncryptionPolicy {
            get {
                return ResourceManager.GetString("DomainDoesNotFollowEncryptionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid operator.
        /// </summary>
        internal static string DomainIsNotAValidOperator {
            get {
                return ResourceManager.GetString("DomainIsNotAValidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name is invalid.
        /// </summary>
        internal static string DomainNameIsInvalid {
            get {
                return ResourceManager.GetString("DomainNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        internal static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following is some general information about the contract..
        /// </summary>
        internal static string GeneralInformationInfoText {
            get {
                return ResourceManager.GetString("GeneralInformationInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Function.
        /// </summary>
        internal static string HashFunction {
            get {
                return ResourceManager.GetString("HashFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human readable text.
        /// </summary>
        internal static string HumanReadableText {
            get {
                return ResourceManager.GetString("HumanReadableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I approve of my personal information to be associated with the legal identity I am reviewing, for the purposes of transparency..
        /// </summary>
        internal static string IApproveOfMyPersonalInformationToBeAssociated {
            get {
                return ResourceManager.GetString("IApproveOfMyPersonalInformationToBeAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity information.
        /// </summary>
        internal static string IdentityInformation {
            get {
                return ResourceManager.GetString("IdentityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is personal information registered for the party who signed the contract..
        /// </summary>
        internal static string IdentityInformationInfoText {
            get {
                return ResourceManager.GetString("IdentityInformationInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have carefully reviewed all information above, and find it to be a correct representation of the person requesting the review:.
        /// </summary>
        internal static string IHaveCarefullyReviewedAllInformationAbove {
            get {
                return ResourceManager.GetString("IHaveCarefullyReviewedAllInformationAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite peer to review.
        /// </summary>
        internal static string InvitePeerToReview {
            get {
                return ResourceManager.GetString("InvitePeerToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name(s).
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Id.
        /// </summary>
        internal static string LegalId {
            get {
                return ResourceManager.GetString("LegalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local name.
        /// </summary>
        internal static string LocalName {
            get {
                return ResourceManager.GetString("LocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An overview of the machine-readable data embedded in the contract is shown below..
        /// </summary>
        internal static string MachineReadableInfoText {
            get {
                return ResourceManager.GetString("MachineReadableInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine readable information.
        /// </summary>
        internal static string MachineReadableText {
            get {
                return ResourceManager.GetString("MachineReadableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAG.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name(s).
        /// </summary>
        internal static string MiddleNames {
            get {
                return ResourceManager.GetString("MiddleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Contracts.
        /// </summary>
        internal static string MyContracts {
            get {
                return ResourceManager.GetString("MyContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is a list of contracts. Click on a contract for more information about it..
        /// </summary>
        internal static string MyContractsInfoText {
            get {
                return ResourceManager.GetString("MyContractsInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Created Contracts.
        /// </summary>
        internal static string MyCreatedContracts {
            get {
                return ResourceManager.GetString("MyCreatedContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract.
        /// </summary>
        internal static string NewContract {
            get {
                return ResourceManager.GetString("NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contracts found..
        /// </summary>
        internal static string NoContractsFound {
            get {
                return ResourceManager.GetString("NoContractsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notary.
        /// </summary>
        internal static string Notary {
            get {
                return ResourceManager.GetString("Notary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to the operator.
        /// </summary>
        internal static string NotConnectedToTheOperator {
            get {
                return ResourceManager.GetString("NotConnectedToTheOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete contract.
        /// </summary>
        internal static string ObsoleteContract {
            get {
                return ResourceManager.GetString("ObsoleteContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator does not support legal identities and smart contracts.
        /// </summary>
        internal static string OperatorDoesNotSupportLegalIdentitiesAndSmartContracts {
            get {
                return ResourceManager.GetString("OperatorDoesNotSupportLegalIdentitiesAndSmartContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator {0} does not support registration of new accounts.
        /// </summary>
        internal static string OperatorDoesNotSupportRegisteringNewAccounts {
            get {
                return ResourceManager.GetString("OperatorDoesNotSupportRegisteringNewAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Other&gt;.
        /// </summary>
        internal static string OperatorDomainOther {
            get {
                return ResourceManager.GetString("OperatorDomainOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract parameters are shown below, together with their corresponding values..
        /// </summary>
        internal static string ParametersInfoText {
            get {
                return ResourceManager.GetString("ParametersInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The (expected) parts defined for the contract is listed below..
        /// </summary>
        internal static string PartsInfoText {
            get {
                return ResourceManager.GetString("PartsInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid.
        /// </summary>
        internal static string PasswordIsInvalid {
            get {
                return ResourceManager.GetString("PasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer Review.
        /// </summary>
        internal static string PeerReview {
            get {
                return ResourceManager.GetString("PeerReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer review accepted.
        /// </summary>
        internal static string PeerReviewAccepted {
            get {
                return ResourceManager.GetString("PeerReviewAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer review rejected.
        /// </summary>
        internal static string PeerReviewRejected {
            get {
                return ResourceManager.GetString("PeerReviewRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal/legal information.
        /// </summary>
        internal static string PersonalLegalInformation {
            get {
                return ResourceManager.GetString("PersonalLegalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to get a wallet, perform transactions and sign smart contracts, you need an attested personal or legal identity assigned to your account..
        /// </summary>
        internal static string PersonalLegalInfoText {
            get {
                return ResourceManager.GetString("PersonalLegalInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal number.
        /// </summary>
        internal static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The personal number does not match national personal number regulations.
        /// </summary>
        internal static string PersonalNumberDoesNotMatchCountry {
            get {
                return ResourceManager.GetString("PersonalNumberDoesNotMatchCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The personal number does not match national personal number regulations. Expected format: .
        /// </summary>
        internal static string PersonalNumberDoesNotMatchCountry_ExpectedFormat {
            get {
                return ResourceManager.GetString("PersonalNumberDoesNotMatchCountry_ExpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Number ({0}).
        /// </summary>
        internal static string PersonalNumberPlaceholder {
            get {
                return ResourceManager.GetString("PersonalNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition.
        /// </summary>
        internal static string Petition {
            get {
                return ResourceManager.GetString("Petition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition Contract.
        /// </summary>
        internal static string PetitionContract {
            get {
                return ResourceManager.GetString("PetitionContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition for the personal data in one of your contracts has been received. Review the information below and choose how you wish to respond..
        /// </summary>
        internal static string PetitionContractInformationText {
            get {
                return ResourceManager.GetString("PetitionContractInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition Identity.
        /// </summary>
        internal static string PetitionIdentity {
            get {
                return ResourceManager.GetString("PetitionIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition for the personal data of your legal identity has been received. Review the information below and choose how you wish to respond..
        /// </summary>
        internal static string PetitionIdentityInformationText {
            get {
                return ResourceManager.GetString("PetitionIdentityInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition sent.
        /// </summary>
        internal static string PetitionSent {
            get {
                return ResourceManager.GetString("PetitionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition to view contract was denied..
        /// </summary>
        internal static string PetitionToViewContractWasDenied {
            get {
                return ResourceManager.GetString("PetitionToViewContractWasDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition to view legal identity was denied..
        /// </summary>
        internal static string PetitionToViewLegalIdentityWasDenied {
            get {
                return ResourceManager.GetString("PetitionToViewLegalIdentityWasDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is too large.
        /// </summary>
        internal static string PhotoIsTooLarge {
            get {
                return ResourceManager.GetString("PhotoIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick photo.
        /// </summary>
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is invalid.
        /// </summary>
        internal static string PinIsInvalid {
            get {
                return ResourceManager.GetString("PinIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN number must not include leading or trailing whitespace..
        /// </summary>
        internal static string PinMustNotIncludeWhitespace {
            get {
                return ResourceManager.GetString("PinMustNotIncludeWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN or password.
        /// </summary>
        internal static string PinOrPassword {
            get {
                return ResourceManager.GetString("PinOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PINs do not match.
        /// </summary>
        internal static string PinsDoNotMatch {
            get {
                return ResourceManager.GetString("PinsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN number too short. At least {0} numbers (or characters) are required..
        /// </summary>
        internal static string PinTooShort {
            get {
                return ResourceManager.GetString("PinTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review all information above, and check the corresponding check boxes if the information is correct. This must be done before you can approve the information..
        /// </summary>
        internal static string PleaseReviewAndCheckAllCheckboxes {
            get {
                return ResourceManager.GetString("PleaseReviewAndCheckAllCheckboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose.
        /// </summary>
        internal static string Propose {
            get {
                return ResourceManager.GetString("Propose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter manually.
        /// </summary>
        internal static string QrEnterManually {
            get {
                return ResourceManager.GetString("QrEnterManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan code.
        /// </summary>
        internal static string QrScanCode {
            get {
                return ResourceManager.GetString("QrScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Identity:.
        /// </summary>
        internal static string QrScanLegalIdentity {
            get {
                return ResourceManager.GetString("QrScanLegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align the QR-Code within the frame.
        /// </summary>
        internal static string QrScanOverlay {
            get {
                return ResourceManager.GetString("QrScanOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region or State.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Information.
        /// </summary>
        internal static string RejectInformation {
            get {
                return ResourceManager.GetString("RejectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report as Compromized.
        /// </summary>
        internal static string ReportAsCompromized {
            get {
                return ResourceManager.GetString("ReportAsCompromized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting entity.
        /// </summary>
        internal static string RequestingEntity {
            get {
                return ResourceManager.GetString("RequestingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out.
        /// </summary>
        internal static string RequestTimedOut {
            get {
                return ResourceManager.GetString("RequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was cancelled.
        /// </summary>
        internal static string RequestWasCancelled {
            get {
                return ResourceManager.GetString("RequestWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        internal static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype PIN or password.
        /// </summary>
        internal static string RetypePinOrPassword {
            get {
                return ResourceManager.GetString("RetypePinOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been requested to review the following personal information. If correct, check the corresponding boxes, and press the Approve button at the bottom. You can also press the Reject button if you find anything that is incorrect..
        /// </summary>
        internal static string ReviewIdentityInformationText {
            get {
                return ResourceManager.GetString("ReviewIdentityInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke.
        /// </summary>
        internal static string RevokeInformation {
            get {
                return ResourceManager.GetString("RevokeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can see the different roles defined for the contract. If more than one part is assumed for a role, this number will be shown in the description of the role..
        /// </summary>
        internal static string RolesInfoText {
            get {
                return ResourceManager.GetString("RolesInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a photo is not supported on this device.
        /// </summary>
        internal static string SelectingAPhotoIsNotSupported {
            get {
                return ResourceManager.GetString("SelectingAPhotoIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Operator.
        /// </summary>
        internal static string SelectOperator {
            get {
                return ResourceManager.GetString("SelectOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the category of contract to create..
        /// </summary>
        internal static string SelectTheCategoryOfContractToCreate {
            get {
                return ResourceManager.GetString("SelectTheCategoryOfContractToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of contract to create..
        /// </summary>
        internal static string SelectTheTypeOfContractToCreate {
            get {
                return ResourceManager.GetString("SelectTheTypeOfContractToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select who should have access to this contract..
        /// </summary>
        internal static string SelectWhoShouldHaveAccessToThisContract {
            get {
                return ResourceManager.GetString("SelectWhoShouldHaveAccessToThisContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your role in this contract..
        /// </summary>
        internal static string SelectYourRole {
            get {
                return ResourceManager.GetString("SelectYourRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your role in this contract..
        /// </summary>
        internal static string SelectYourRoleInThisContract {
            get {
                return ResourceManager.GetString("SelectYourRoleInThisContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Signature.
        /// </summary>
        internal static string ServerSignature {
            get {
                return ResourceManager.GetString("ServerSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is information related to a server signature..
        /// </summary>
        internal static string ServerSignatureInformationInfoText {
            get {
                return ResourceManager.GetString("ServerSignatureInformationInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Signatures.
        /// </summary>
        internal static string ServerSignatures {
            get {
                return ResourceManager.GetString("ServerSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integrity of the contract is protected by the server signature shown below..
        /// </summary>
        internal static string ServerSignaturesInfoText {
            get {
                return ResourceManager.GetString("ServerSignaturesInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign after.
        /// </summary>
        internal static string SignAfter {
            get {
                return ResourceManager.GetString("SignAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign as {0}.
        /// </summary>
        internal static string SignAsRole {
            get {
                return ResourceManager.GetString("SignAsRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature information.
        /// </summary>
        internal static string SignatureInformation {
            get {
                return ResourceManager.GetString("SignatureInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign before.
        /// </summary>
        internal static string SignBefore {
            get {
                return ResourceManager.GetString("SignBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed Contracts.
        /// </summary>
        internal static string SignedContracts {
            get {
                return ResourceManager.GetString("SignedContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking a photo is not supported on this device.
        /// </summary>
        internal static string TakingAPhotoIsNotSupported {
            get {
                return ResourceManager.GetString("TakingAPhotoIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template ID.
        /// </summary>
        internal static string TemplateId {
            get {
                return ResourceManager.GetString("TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contract requires at least {0} part(s) of role {1}. Add more parts to the contract and try again..
        /// </summary>
        internal static string TheContractRequiresAtLeast_AddMoreParts {
            get {
                return ResourceManager.GetString("TheContractRequiresAtLeast_AddMoreParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contract requires at most {0} part(s) of role {1}. Remove some of the parts from the contract and try again..
        /// </summary>
        internal static string TheContractRequiresAtMost_RemoveParts {
            get {
                return ResourceManager.GetString("TheContractRequiresAtMost_RemoveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the connection is {0}. This has been copied to the clipboard..
        /// </summary>
        internal static string ThePasswordForTheConnectionIs {
            get {
                return ResourceManager.GetString("ThePasswordForTheConnectionIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no network.
        /// </summary>
        internal static string ThereIsNoNetwork {
            get {
                return ResourceManager.GetString("ThereIsNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified code is not a legal identity.
        /// </summary>
        internal static string TheSpecifiedCodeIsNotALegalIdentity {
            get {
                return ResourceManager.GetString("TheSpecifiedCodeIsNotALegalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time stamp.
        /// </summary>
        internal static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect to {0}, you need an account. Do you want to create one, or use an existing account?.
        /// </summary>
        internal static string ToConnectToDomainYouNeedAnAccount {
            get {
                return ResourceManager.GetString("ToConnectToDomainYouNeedAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferable.
        /// </summary>
        internal static string Transferable {
            get {
                return ResourceManager.GetString("Transferable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate with {0}.
        /// </summary>
        internal static string UnableToAuthenticateWith {
            get {
                return ResourceManager.GetString("UnableToAuthenticateWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}.
        /// </summary>
        internal static string UnableToConnectTo {
            get {
                return ResourceManager.GetString("UnableToConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use existing.
        /// </summary>
        internal static string UseExisting {
            get {
                return ResourceManager.GetString("UseExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your identity information has to be validated before it can be approved. This can be done manually by your operator. It can also be done by peers..
        /// </summary>
        internal static string ValidateIdentityInfo1Text {
            get {
                return ResourceManager.GetString("ValidateIdentityInfo1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To invite a peer to review your application, you need to scan the ID code of the peer you wish to invite. They will be able to see and review your application. When sufficient peers have reviewed your information, and certified it is correct, the operator will automatically approve your application. The information about who reviewed your identity will be encoded into the reviewed identity itself..
        /// </summary>
        internal static string ValidateIdentityInfo2Text {
            get {
                return ResourceManager.GetString("ValidateIdentityInfo2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the current status of the application below..
        /// </summary>
        internal static string ValidateIdentityInfo3Text {
            get {
                return ResourceManager.GetString("ValidateIdentityInfo3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating information.
        /// </summary>
        internal static string ValidatingInformation {
            get {
                return ResourceManager.GetString("ValidatingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contract.
        /// </summary>
        internal static string ViewContract {
            get {
                return ResourceManager.GetString("ViewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following is personal information registered with the legal identity. Signatures and payments are signed using this information..
        /// </summary>
        internal static string ViewIdentityInformationText {
            get {
                return ResourceManager.GetString("ViewIdentityInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TAG Xamarin App!.
        /// </summary>
        internal static string WelcomeToTagHeading {
            get {
                return ResourceManager.GetString("WelcomeToTagHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect to the TAG network, you need to select an operator. Please select one from the list below..
        /// </summary>
        internal static string WelcomeToTagSubheading {
            get {
                return ResourceManager.GetString("WelcomeToTagSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating network identity.
        /// </summary>
        internal static string XmppState_Authenticating {
            get {
                return ResourceManager.GetString("XmppState_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding connection.
        /// </summary>
        internal static string XmppState_Binding {
            get {
                return ResourceManager.GetString("XmppState_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string XmppState_Connected {
            get {
                return ResourceManager.GetString("XmppState_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection.
        /// </summary>
        internal static string XmppState_Connecting {
            get {
                return ResourceManager.GetString("XmppState_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string XmppState_Error {
            get {
                return ResourceManager.GetString("XmppState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching roster.
        /// </summary>
        internal static string XmppState_FetchingRoster {
            get {
                return ResourceManager.GetString("XmppState_FetchingRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string XmppState_Offline {
            get {
                return ResourceManager.GetString("XmppState_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering with broker.
        /// </summary>
        internal static string XmppState_Registering {
            get {
                return ResourceManager.GetString("XmppState_Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting session.
        /// </summary>
        internal static string XmppState_RequestingSession {
            get {
                return ResourceManager.GetString("XmppState_RequestingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting presence.
        /// </summary>
        internal static string XmppState_SettingPresence {
            get {
                return ResourceManager.GetString("XmppState_SettingPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting connection.
        /// </summary>
        internal static string XmppState_StartingEncryption {
            get {
                return ResourceManager.GetString("XmppState_StartingEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiating stream.
        /// </summary>
        internal static string XmppState_StreamNegotiation {
            get {
                return ResourceManager.GetString("XmppState_StreamNegotiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream established.
        /// </summary>
        internal static string XmppState_StreamOpened {
            get {
                return ResourceManager.GetString("XmppState_StreamOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can protect your wallet and sensitive information by adding an additional PIN number or password..
        /// </summary>
        internal static string YouCanProtectYourWalletPinInfo {
            get {
                return ResourceManager.GetString("YouCanProtectYourWalletPinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to approve to associate your personal information with the identity you review. When third parties review the information in the identity, they will have access to the identity of the reviewers, for transparency..
        /// </summary>
        internal static string YouNeedToApproveToAssociate {
            get {
                return ResourceManager.GetString("YouNeedToApproveToAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to check the box you have carefully reviewed all corresponding information above..
        /// </summary>
        internal static string YouNeedToCheckCarefullyReviewed {
            get {
                return ResourceManager.GetString("YouNeedToCheckCarefullyReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a country.
        /// </summary>
        internal static string YouNeedToProvideACountry {
            get {
                return ResourceManager.GetString("YouNeedToProvideACountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide a first name.
        /// </summary>
        internal static string YouNeedToProvideAFirstName {
            get {
                return ResourceManager.GetString("YouNeedToProvideAFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide at least one last name.
        /// </summary>
        internal static string YouNeedToProvideALastName {
            get {
                return ResourceManager.GetString("YouNeedToProvideALastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide a personal or social security number.
        /// </summary>
        internal static string YouNeedToProvideAPersonalNumber {
            get {
                return ResourceManager.GetString("YouNeedToProvideAPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contract contains errors. Fix these errors and try again..
        /// </summary>
        internal static string YourContractContainsErrors {
            get {
                return ResourceManager.GetString("YourContractContainsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Role.
        /// </summary>
        internal static string YourRole {
            get {
                return ResourceManager.GetString("YourRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip or Postal Code.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
