//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag.Neuron.Xamarin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tag.Neuron.Xamarin.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name {0} is already taken. Choose another..
        /// </summary>
        internal static string AccountNameAlreadyTaken {
            get {
                return ResourceManager.GetString("AccountNameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to {0}.
        /// </summary>
        internal static string CantConnectTo {
            get {
                return ResourceManager.GetString("CantConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue anyway.
        /// </summary>
        internal static string ContinueAnyway {
            get {
                return ResourceManager.GetString("ContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems like the database hasn&apos;t been closed correctly, and may therefore be damaged. An attempt can be made to repair the database by first wiping it. How would you like to proceed?.
        /// </summary>
        internal static string DatabaseCorruptInfoText {
            get {
                return ResourceManager.GetString("DatabaseCorruptInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database issue.
        /// </summary>
        internal static string DatabaseIssue {
            get {
                return ResourceManager.GetString("DatabaseIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database repair failed. We&apos;re out of options now, so continue at your own risk..
        /// </summary>
        internal static string DatabaseRepairFailedInfoText {
            get {
                return ResourceManager.GetString("DatabaseRepairFailedInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not follow the ubiquitous encryption policy.
        /// </summary>
        internal static string DomainDoesNotFollowEncryptionPolicy {
            get {
                return ResourceManager.GetString("DomainDoesNotFollowEncryptionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid operator.
        /// </summary>
        internal static string DomainIsNotAValidOperator {
            get {
                return ResourceManager.GetString("DomainIsNotAValidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close page.
        /// </summary>
        internal static string FailedToClosePage {
            get {
                return ResourceManager.GetString("FailedToClosePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to navigate to page {0}  {1}.
        /// </summary>
        internal static string FailedToNavigateToPage {
            get {
                return ResourceManager.GetString("FailedToNavigateToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IoT Discovery Code.
        /// </summary>
        internal static string InvalidIoTDiscoveryCode {
            get {
                return ResourceManager.GetString("InvalidIoTDiscoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator {0} does not support registration of new accounts.
        /// </summary>
        internal static string OperatorDoesNotSupportRegisteringNewAccounts {
            get {
                return ResourceManager.GetString("OperatorDoesNotSupportRegisteringNewAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair and continue.
        /// </summary>
        internal static string RepairAndContinue {
            get {
                return ResourceManager.GetString("RepairAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out.
        /// </summary>
        internal static string RequestTimedOut {
            get {
                return ResourceManager.GetString("RequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was cancelled.
        /// </summary>
        internal static string RequestWasCancelled {
            get {
                return ResourceManager.GetString("RequestWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no network.
        /// </summary>
        internal static string ThereIsNoNetwork {
            get {
                return ResourceManager.GetString("ThereIsNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate with {0}.
        /// </summary>
        internal static string UnableToAuthenticateWith {
            get {
                return ResourceManager.GetString("UnableToAuthenticateWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}.
        /// </summary>
        internal static string UnableToConnectTo {
            get {
                return ResourceManager.GetString("UnableToConnectTo", resourceCulture);
            }
        }
    }
}
