..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.pt.resx" -tl pt
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.es.resx" -tl es
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.de.resx" -tl de
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.fr.resx" -tl fr
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.da.resx" -tl da
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.no.resx" -tl no
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.fi.resx" -tl fi
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.sr.resx" -tl sr
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.ro.resx" -tl ro
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp\Resx\AppResources.resx" -rl en -tf "..\IdApp\IdApp\Resx\AppResources.ru.resx" -tl ru


..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.pt.resx" -tl pt
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.es.resx" -tl es
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.de.resx" -tl de
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.fr.resx" -tl fr
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.da.resx" -tl da
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.no.resx" -tl no
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.fi.resx" -tl fi
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.sr.resx" -tl sr
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.ro.resx" -tl ro
..\..\IoTGateway\Utilities\Waher.Utility.Translate\bin\Debug\net6.0\Waher.Utility.Translate.exe -d "C:\ProgramData\Translations\IdApp" -e -rf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.resx" -rl en -tf "..\IdApp\IdApp.iOS\Resources\Resx\PListResources.ru.resx" -tl ru

